/**
 * DOM and SSR lowering metadata generated from the canonical widget registry.
 * DO NOT EDIT: run `pnpm widgets:generate`.
 */
export const PRIMITIVE_NATIVE_ELEMENTS: Readonly<Record<string, string>> = Object.freeze({
  Accordion: "details",
  Audio: "audio",
  Avatar: "span",
  Badge: "span",
  Breadcrumb: "nav",
  Button: "button",
  Canvas: "canvas",
  Checkbox: "input",
  DataTable: "table",
  DatePicker: "input",
  Divider: "hr",
  Drawer: "aside",
  ErrorSummary: "div",
  FieldError: "span",
  FieldGroup: "fieldset",
  FileUpload: "input",
  Form: "form",
  FormError: "div",
  Icon: "span",
  IFrame: "iframe",
  Image: "img",
  Input: "input",
  Link: "a",
  List: "ul",
  Modal: "dialog",
  Popover: "div",
  ProgressBar: "progress",
  Radio: "input",
  ScrollView: "div",
  Select: "select",
  Skeleton: "div",
  Slider: "input",
  Spinner: "span",
  Switch: "input",
  Tabs: "div",
  Text: "span",
  TextArea: "textarea",
  Title: "h1",
  Toast: "div",
  Tooltip: "span",
  Video: "video",
  View: "div",
  VirtualList: "div",
});

export const PRIMITIVE_CALL_PROPERTIES: Readonly<Record<string, string>> = Object.freeze({
  Accordion: "title",
  Badge: "label",
  Button: "label",
  DatePicker: "value",
  Input: "value",
  Link: "text",
  Select: "value",
  Text: "text",
  TextArea: "value",
  Title: "text",
});
