import { packageLibrary } from '@vx-foundation/core/package';
import pc from 'picocolors';

export interface PackageCommandOptions {
  out?: string;
}

export function packageCommand(root: string = process.cwd(), options: PackageCommandOptions = {}): void {
  const result = packageLibrary(root, {
    ...(options.out ? { outDir: options.out } : {})
  });
  const errors = result.diagnostics.filter((diagnostic) => diagnostic.severity === 'error');
  for (const diagnostic of result.diagnostics) {
    const location = `${diagnostic.span.filePath}:${diagnostic.span.start.line}:${diagnostic.span.start.column}`;
    const output = `[${diagnostic.code}] ${diagnostic.message} (${location})`;
    console.error(diagnostic.severity === 'error' ? pc.red(output) : pc.yellow(output));
  }
  if (errors.length > 0 || !result.manifest) {
    throw new Error(`VX package creation failed with ${errors.length} error${errors.length === 1 ? '' : 's'}.`);
  }

  console.log(pc.green(`VX package staged at ${result.outDir}`));
  console.log(pc.cyan(`Discovered ${result.publicEntries.length} public module${result.publicEntries.length === 1 ? '' : 's'}:`));
  for (const entry of result.publicEntries) console.log(`  ${entry.exportKey} -> ${entry.sourcePath}`);
  console.log(pc.dim('The export map and VX manifest were generated by the framework.'));
}
