/**
 * Compiler validation groups generated from the canonical widget registry.
 * DO NOT EDIT: run `pnpm widgets:generate`.
 */
export const CONTAINER_WIDGETS = new Set([
    "Accordion",
    "Breadcrumb",
    "DataTable",
    "Drawer",
    "ErrorSummary",
    "FieldGroup",
    "Form",
    "List",
    "Modal",
    "Popover",
    "ScrollView",
    "Tabs",
    "Toast",
    "Tooltip",
    "View",
    "VirtualList"
  ]);
export const TEXT_WIDGETS = new Set([
    "Avatar",
    "Badge",
    "Button",
    "FieldError",
    "FormError",
    "Link",
    "Text",
    "Title"
  ]);
export const CONTROL_WIDGETS = new Set([
    "Button",
    "Checkbox",
    "DatePicker",
    "FileUpload",
    "Input",
    "Radio",
    "Select",
    "Slider",
    "Switch",
    "TextArea"
  ]);
export const MEDIA_WIDGETS = new Set([
    "Audio",
    "Canvas",
    "Icon",
    "IFrame",
    "Image",
    "Video"
  ]);
export const FORM_CONTROL_WIDGETS = new Set([
    "Checkbox",
    "DatePicker",
    "FileUpload",
    "Input",
    "Radio",
    "Select",
    "Slider",
    "Switch",
    "TextArea"
  ]);
export const INTERACTIVE_WIDGETS = new Set([
    "Accordion",
    "Audio",
    "Button",
    "Checkbox",
    "DatePicker",
    "Drawer",
    "FileUpload",
    "Input",
    "Link",
    "Modal",
    "Popover",
    "Radio",
    "Select",
    "Slider",
    "Switch",
    "Tabs",
    "TextArea",
    "Video"
  ]);
export const PRIMITIVE_WIDGETS = new Set([
    "Accordion",
    "Audio",
    "Avatar",
    "Badge",
    "Breadcrumb",
    "Button",
    "Canvas",
    "Checkbox",
    "DataTable",
    "DatePicker",
    "Divider",
    "Drawer",
    "ErrorSummary",
    "FieldError",
    "FieldGroup",
    "FileUpload",
    "Form",
    "FormError",
    "Icon",
    "IFrame",
    "Image",
    "Input",
    "Link",
    "List",
    "Modal",
    "Popover",
    "ProgressBar",
    "Radio",
    "ScrollView",
    "Select",
    "Skeleton",
    "Slider",
    "Spinner",
    "Switch",
    "Tabs",
    "Text",
    "TextArea",
    "Title",
    "Toast",
    "Tooltip",
    "Video",
    "View",
    "VirtualList"
  ]);
