/**
 * VX Compiler - Primitive Widget Registry
 * 
 * This file is automatically generated. It exports the names and raw source
 * definitions of all native primitives known to the VX compiler.
 */

export const PRIMITIVE_NAMES = [
  'Audio',
  'Button',
  'Canvas',
  'Checkbox',
  'Divider',
  'ErrorSummary',
  'FieldError',
  'FieldGroup',
  'Form',
  'FormError',
  'IFrame',
  'Icon',
  'Image',
  'Input',
  'Link',
  'List',
  'ProgressBar',
  'Radio',
  'ScrollView',
  'Select',
  'Slider',
  'Switch',
  'Text',
  'TextArea',
  'Title',
  'Video',
  'View',
];

export const PRIMITIVE_SOURCES: Record<string, string> = {
  'Audio': `#script
  prop src: String
  prop autoPlay: Optional<Bool> = false
  prop controls: Optional<Bool> = true
  prop loop: Optional<Bool> = false
  prop muted: Optional<Bool> = false
  prop preload: Optional<String> = "metadata"

  prop play: Optional<Event<Void>>
  prop pause: Optional<Event<Void>>
  prop end: Optional<Event<Void>>
  prop timeUpdate: Optional<Event<Float>>
#end script
`,
  'Button': `#script
  prop label: Optional<String>
  prop variant: Optional<String> = "primary"
  prop size: Optional<String> = "medium"
  prop disabled: Optional<Bool> = false
  prop loading: Optional<Bool> = false
  prop fullWidth: Optional<Bool> = false
  prop type: Optional<String> = "button"
  prop iconLeft: Optional<String>
  prop iconRight: Optional<String>
  prop form: Optional<String>

  prop click: Optional<Event<Void>>
  prop focus: Optional<Event<Void>>
  prop blur: Optional<Event<Void>>
#end script
`,
  'Canvas': `#script
  prop width: String
  prop height: String
  prop contextType: Optional<String> = "2d"

  prop ready: Optional<Event<Any>>
  prop click: Optional<Event<Any>>
#end script
`,
  'Checkbox': `#script
  prop field: Optional<String>
  prop checked: Optional<Bool>
  prop label: Optional<String>
  prop disabled: Optional<Bool> = false
  prop required: Optional<Bool> = false
  prop indeterminate: Optional<Bool> = false
  prop name: Optional<String>
  prop value: Optional<String>
  prop size: Optional<String> = "medium"
  prop color: Optional<String> = "primary"

  prop error: Optional<String>

  prop change: Optional<Event<Bool>>
  prop focus: Optional<Event<Void>>
  prop blur: Optional<Event<Void>>
#end script
`,
  'Divider': `#script
  prop orientation: Optional<String> = "horizontal"
  prop thickness: Optional<String> = "1px"
  prop color: Optional<String>
  prop margin: Optional<String>
  prop variant: Optional<String> = "solid"
#end script
`,
  'ErrorSummary': `#script
  prop controller: Any
  prop title: Optional<String> = "Please correct the following errors."
  prop role: Optional<String> = "alert"
#end script
`,
  'FieldError': `#script
  prop field: String
  prop role: Optional<String> = "alert"
#end script
`,
  'FieldGroup': `#script
  prop label: Optional<String>
  prop description: Optional<String>
  prop required: Optional<Bool> = false
#end script
`,
  'Form': `#script
  prop controller: Optional<Any>
  prop action: Optional<String>
  prop method: Optional<String> = "post"
  prop autocomplete: Optional<String>
  prop noValidate: Optional<Bool> = false

  prop submit: Optional<Event<Any>>
  prop reset: Optional<Event<Void>>
#end script
`,
  'FormError': `#script
  prop controller: Any
  prop role: Optional<String> = "alert"
#end script
`,
  'IFrame': `#script
  prop src: String
  prop title: Optional<String>
  prop width: Optional<String> = "100%"
  prop height: Optional<String> = "100%"
  prop loading: Optional<String> = "lazy"
  prop allowFullScreen: Optional<Bool> = false
  prop allow: Optional<String>
  prop referrerPolicy: Optional<String>
  prop sandbox: Optional<String>
  prop trusted: Optional<Bool> = false

  prop load: Optional<Event<Void>>
  prop error: Optional<Event<String>>
#end script
`,
  'Icon': `#script
  prop name: String
  prop size: Optional<String> = "24px"
  prop color: Optional<String> = "currentColor"
  prop decorative: Optional<Bool> = true
  prop weight: Optional<String>
  prop variant: Optional<String> = "outline"
  prop strokeWidth: Optional<Float>
  prop viewBox: Optional<String>

  prop click: Optional<Event<Void>>
#end script
`,
  'Image': `#script
  prop src: String
  prop alt: Optional<String> = ""
  prop decorative: Optional<Bool> = false
  prop objectFit: Optional<String> = "cover"
  prop objectPosition: Optional<String> = "center"
  prop width: Optional<String>
  prop height: Optional<String>
  prop loading: Optional<String> = "lazy"
  prop crossOrigin: Optional<String>
  prop cornerRadius: Optional<String>
  prop fallbackSrc: Optional<String>

  prop load: Optional<Event<Void>>
  prop error: Optional<Event<Void>>
#end script
`,
  'Input': `#script
  prop field: Optional<String>
  prop value: Optional<String>
  prop type: Optional<String> = "text"
  prop placeholder: Optional<String> = ""
  prop label: Optional<String>
  prop disabled: Optional<Bool> = false
  prop readonly: Optional<Bool> = false
  prop required: Optional<Bool> = false
  prop name: Optional<String>
  prop autoComplete: Optional<String>
  prop autoFocus: Optional<Bool> = false
  prop maxLength: Optional<Int>
  prop minLength: Optional<Int>
  prop pattern: Optional<String>

  prop error: Optional<String>
  prop helperText: Optional<String>

  prop change: Optional<Event<String>>
  prop focus: Optional<Event<Void>>
  prop blur: Optional<Event<Void>>
  prop keyDown: Optional<Event<String>>
  prop keyUp: Optional<Event<String>>
#end script
`,
  'Link': `#script
  prop href: String
  prop text: Optional<String>
  prop target: Optional<String> = "_self"
  prop rel: Optional<String>
  prop color: Optional<String>
  prop underline: Optional<String> = "hover"
  prop size: Optional<String>
  prop weight: Optional<String>

  prop click: Optional<Event<Void>>
#end script
`,
  'List': `#script
  prop items: List<Any>
  prop emptyText: Optional<String>
  prop spacing: Optional<String> = "0px"
  prop layout: Optional<String> = "column"
  prop wrap: Optional<Bool> = false
  prop keyExtractor: Optional<String>
  prop onEndReached: Optional<Event<Void>>
  prop onEndReachedThreshold: Optional<Float> = 0.5
  prop refreshing: Optional<Bool> = false
  prop onRefresh: Optional<Event<Void>>
#end script
`,
  'ProgressBar': `#script
  prop value: Float
  prop max: Optional<Float> = 100
  prop variant: Optional<String> = "determinate"
  prop size: Optional<String> = "medium"
  prop color: Optional<String> = "primary"
  prop showLabel: Optional<Bool> = false
#end script
`,
  'Radio': `#script
  prop field: Optional<String>
  prop selected: Optional<Bool>
  prop label: Optional<String>
  prop value: Optional<String>
  prop name: String
  prop disabled: Optional<Bool> = false
  prop required: Optional<Bool> = false
  prop size: Optional<String> = "medium"
  prop color: Optional<String> = "primary"

  prop error: Optional<String>

  prop change: Optional<Event<String>>
#end script
`,
  'ScrollView': `#script
  prop direction: Optional<String> = "vertical"
  prop showsIndicators: Optional<Bool> = true
  prop padding: Optional<String>
  prop margin: Optional<String>
  prop background: Optional<String>
  prop width: Optional<String>
  prop height: Optional<String>
  prop maxHeight: Optional<String>
  prop maxWidth: Optional<String>
  prop contentContainerStyle: Optional<String>
  prop scrollEventThrottle: Optional<Int> = 16
  prop bounces: Optional<Bool> = true

  prop scroll: Optional<Event<Any>>
  prop scrollBeginDrag: Optional<Event<Void>>
  prop scrollEndDrag: Optional<Event<Void>>
#end script
`,
  'Select': `#script
  prop field: Optional<String>
  prop value: Optional<String>
  prop options: List<Any>
  prop placeholder: Optional<String>
  prop disabled: Optional<Bool> = false
  prop required: Optional<Bool> = false
  prop multiple: Optional<Bool> = false
  prop name: Optional<String>
  prop size: Optional<String> = "medium"

  prop error: Optional<String>
  prop helperText: Optional<String>

  prop change: Optional<Event<String>>
  prop focus: Optional<Event<Void>>
  prop blur: Optional<Event<Void>>
#end script
`,
  'Slider': `#script
  prop field: Optional<String>
  prop value: Optional<Float>
  prop min: Optional<Float> = 0
  prop max: Optional<Float> = 100
  prop step: Optional<Float> = 1
  prop disabled: Optional<Bool> = false
  prop orientation: Optional<String> = "horizontal"
  prop marks: Optional<Bool> = false
  prop color: Optional<String> = "primary"
  prop name: Optional<String>

  prop change: Optional<Event<Float>>
  prop dragStart: Optional<Event<Void>>
  prop dragEnd: Optional<Event<Float>>
#end script
`,
  'Switch': `#script
  prop field: Optional<String>
  prop checked: Optional<Bool>
  prop disabled: Optional<Bool> = false
  prop label: Optional<String>
  prop labelPlacement: Optional<String> = "end"
  prop size: Optional<String> = "medium"
  prop color: Optional<String> = "primary"
  prop name: Optional<String>

  prop change: Optional<Event<Bool>>
#end script
`,
  'Text': `#script
  prop text: String
  prop size: Optional<String>
  prop weight: Optional<String> = "normal"
  prop color: Optional<String>
  prop align: Optional<String> = "left"
  prop lineHeight: Optional<String>
  prop letterSpacing: Optional<String>
  prop textDecoration: Optional<String>
  prop textTransform: Optional<String>
  prop fontFamily: Optional<String>
  prop maxLines: Optional<Int>
  prop truncate: Optional<Bool> = false
  prop selectable: Optional<Bool> = true
  prop margin: Optional<String>
#end script
`,
  'TextArea': `#script
  prop field: Optional<String>
  prop value: Optional<String>
  prop placeholder: Optional<String> = ""
  prop rows: Optional<Int> = 3
  prop minRows: Optional<Int>
  prop maxRows: Optional<Int>
  prop disabled: Optional<Bool> = false
  prop readonly: Optional<Bool> = false
  prop required: Optional<Bool> = false
  prop maxLength: Optional<Int>
  prop resize: Optional<String> = "none"
  prop name: Optional<String>

  prop error: Optional<String>
  prop helperText: Optional<String>

  prop change: Optional<Event<String>>
  prop focus: Optional<Event<Void>>
  prop blur: Optional<Event<Void>>
  prop keyDown: Optional<Event<String>>
#end script
`,
  'Title': `#script
  prop text: String
  prop level: Optional<Int> = 1
  prop id: Optional<String>
#end script
`,
  'Video': `#script
  prop src: String
  prop poster: Optional<String>
  prop autoPlay: Optional<Bool> = false
  prop controls: Optional<Bool> = true
  prop loop: Optional<Bool> = false
  prop muted: Optional<Bool> = false
  prop playsInline: Optional<Bool> = true
  prop preload: Optional<String> = "metadata"
  prop width: Optional<String>
  prop height: Optional<String>
  prop objectFit: Optional<String> = "cover"
  prop cornerRadius: Optional<String>

  prop play: Optional<Event<Void>>
  prop pause: Optional<Event<Void>>
  prop end: Optional<Event<Void>>
  prop timeUpdate: Optional<Event<Float>>
  prop error: Optional<Event<String>>
#end script
`,
  'View': `#script
  prop layout: Optional<String> = "column"
  prop align: Optional<String> = "stretch"
  prop justify: Optional<String> = "start"
  prop spacing: Optional<Int> = 0
  prop wrap: Optional<Bool> = false
  prop width: Optional<String>
  prop height: Optional<String>
  prop minWidth: Optional<String>
  prop minHeight: Optional<String>
  prop maxWidth: Optional<String>
  prop maxHeight: Optional<String>
  prop padding: Optional<String>
  prop margin: Optional<String>
  prop background: Optional<String>
  prop cornerRadius: Optional<String>
  prop border: Optional<String>
  prop shadow: Optional<String>
  prop opacity: Optional<Float>
  prop overflow: Optional<String>
  prop position: Optional<String>
  prop zIndex: Optional<Int>
  prop cursor: Optional<String>

  prop click: Optional<Event<Void>>
  prop mouseEnter: Optional<Event<Void>>
  prop mouseLeave: Optional<Event<Void>>
#end script
`,
};
