import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '..');
const read = (path) => readFileSync(resolve(root, path), 'utf8');
const cli = read('packages/cli/src/cli.ts');
for (const command of ['new <name>','dev [root]','build [root]','preview [root]','test [root]','check [target]','format [target]','lint [target]','inspect <file>','migrate [target]','add <package>','remove <package>','update [package]','doctor [root]','publish [root]']) assert.ok(cli.includes(`command('${command}'`), `Missing CLI command: vx ${command}`);
const service = read('packages/tooling/src/language-service.ts');
for (const method of ['semanticTokens(', 'inlayHints(', 'workspaceSymbols(', 'callHierarchy(', 'typeHierarchy(']) assert.ok(service.includes(method), `Language service is missing ${method}`);
const lsp = read('packages/language-server/src/server.ts');
for (const capability of ['semanticTokensProvider','inlayHintProvider','callHierarchyProvider','typeHierarchyProvider','workspaceSymbolProvider']) assert.ok(lsp.includes(capability), `LSP is missing ${capability}`);
assert.ok(lsp.includes('maxFiles: 20_000') && lsp.includes('maxFileBytes: 2 * 1024 * 1024'), 'Large-workspace limits are missing.');
const vscode = JSON.parse(read('packages/vscode-extension/package.json'));
for (const command of ['vx.openPreview','vx.showGeneratedOutput','vx.showGraph','vx.inspectComponent']) assert.ok(vscode.contributes.commands.some((entry) => entry.command === command), `VS Code command ${command} is missing.`);
assert.equal(vscode.contributes.debuggers[0].type, 'vx');
assert.ok(vscode.contributes.breakpoints.some((entry) => entry.language === 'vx'));
const browserManifest = JSON.parse(read('apps/browser-devtools/manifest.json'));
assert.equal(browserManifest.manifest_version, 3);
assert.equal(browserManifest.devtools_page, 'devtools.html');
const runtime = read('packages/runtime/src/devtools.ts');
assert.ok(runtime.includes("Symbol.for('vx.devtools.bridge')") || read('packages/devtools/src/bridge.ts').includes("Symbol.for('vx.devtools.bridge')"));
console.log('Phase 18 structural verification passed.');
